### ISSUE TITLE
iron-flex-layout.html 1.x was providing display: none for [hidden], 2.x doesn't anymore

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-flex-layout#130]
When moving to 2.x (https://github.com/PolymerElements/iron-flex-layout/pull/103/files#diff-ac9bc15ef746292eee06aa75286380c2L62), `iron-flex-layout-classes.html` kept providing this style, but not `iron-flex-layout.html`:
```css
/* IE 10 support for HTML5 hidden attr */
  [hidden] {
    display: none !important;
  }
```
