### ISSUE TITLE
CSS rules not processed correctly by gulp-minifyInline

### ISSUE THREAD

**Issue by opus1269** [PolymerElements/iron-flex-layout#60]
The changes in 1.2.2 caused issues when using minifyInline. Specifically, the rules like this:

```css
     --layout-horizontal: {
      @apply(--layout);

      -ms-flex-direction: row;
      -webkit-flex-direction: row;
      flex-direction: row;
    };
```

aren't processed correctly and break those layouts.

The fix is to move @apply(--layout); to the end instead of the start (not sure why).

I think you know the changes were also a problem in the polymer-starter-kit and caused them to remove minifyInline from their build process. 
https://github.com/PolymerElements/polymer-starter-kit/issues/564
https://github.com/PolymerElements/polymer-starter-kit/issues/561

I know there are caveats about minifying and Polymer because of some of the unique things you folks do with styles, but it had been working fine up to this point and this fix is pretty trivial.

I have a PR ready to fix this if you want it.
