### ISSUE TITLE
enhance layout css

### ISSUE THREAD

**Issue by Herobs** [PolymerElements/iron-flex-layout#93]
https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout-classes.html#L38-L43

``` css
.layout.horizontal,
.layout.vertical {
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}
```

Should be:

``` css
.layout {
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
}
```

Because horizontal layout should be the default. Just like the mixin https://github.com/PolymerElements/iron-flex-layout/blob/master/iron-flex-layout.html#L59-L63
